### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mwohlert** [balena-os/balena-allwinner#101]
Hi,

I noticed that there is no license in this repo, but all of the other repos in balena-os have the apache 2.0 lincense.

Could you clarify on the license here?

**Comment by acostach** [comment]
Thanks for letting us know, it's now being added by https://github.com/balena-os/balena-allwinner/pull/104

**Comment by acostach** [comment]
@mwohlert Thanks for reporting this, license is now present in the repo root too.
