### ISSUE TITLE
[Orange Pi Zero] Use lastest BalenaOS

### ISSUE THREAD

**Issue by giautm** [balena-os/balena-allwinner#119]
Currently, Only v2.31.5 was listing in OS version. The current version of BalenaOS version is v2.50.2.

Why I request this upgrade? I plugged a USB Huawei model into raspberry run BalenaOS version v2.47.0, and it working fine. But, when I trying plug into Orange Pi Zero, It recognized as 
```
12d1:1506 Huawei Technologies Co., Ltd. Modem/Networkcard
```
But not mounted any ttyUSB, I believe it can fixed via OS upgrade (v2.47.0 included [an upgrade for usb-modeswitch](https://github.com/balena-os/meta-balena/blob/master/CHANGELOG.md#v2470)). Or is there any way I can run new version of BalenaOS on my device?

Thank you,

<img width="679" alt="Screen Shot 2020-05-30 at 19 07 05" src="https://user-images.githubusercontent.com/12751435/83327819-f9f4d900-a2a8-11ea-8312-16a1bc8f954d.png">

**Comment by giautm** [comment]
I found the staging environment at https://dashboard.balena-staging.com/, I tried to use `balenaOS 2.48.0+rev5` and very things now working fine.

**Comment by floion** [comment]
Hi, please use the staging environment only for testing. Do not use it for production use cases.
We will update the version in production in the following weeks

**Comment by giautm** [comment]
Hi @floion , any updates on this?

**Comment by giautm** [comment]
Hi @floion any update?

**Comment by floion** [comment]
Hi, no update yet. We have quite a big backlog and we did not yet get to this.
@vicgal can you take this on too since you are looking at Nano Pi?

**Comment by vicgal** [comment]
Update done in https://github.com/balena-os/balena-allwinner/pull/121

**Comment by vicgal** [comment]
Hi @giautm! Orange PI Zero is available in the Balena dashboard at version 2.53.9+rev1

**Comment by giautm** [comment]
Thank you @vicgal for update! I will take a look, <3
