### ISSUE TITLE
Orange Pi Zero does not ship with DEBUGFS support

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-allwinner#128]
Reported on 2.60.1+rev1, balena images have an entry point that mount debugfs and they obviously fail as the support is not in the kernel:
```
cat /proc/config.gz | grep DEBUG_FS
# CONFIG_DEBUG_FS is not set
```
```
balena run -it -e UDEV='on' --privileged balenalib/orange-pi-zero-alpine-node sh
mount: mounting nodev on /sys/kernel/debug failed: No such file or directory
```
See https://jel.ly.fish/fc08efe4-02a4-4ae7-a8c1-42ea48f3c65f

**Comment by alexgg** [comment]
If this is a requirement for balena images, we should make the change in meta-balena.

**Comment by maggie0002** [comment]
> Reported on 2.60.1+rev1, balena images have an entry point that mount debugfs and they obviously fail as the support is not in the kernel:
> 
> ```
> cat /proc/config.gz | grep DEBUG_FS
> # CONFIG_DEBUG_FS is not set
> ```
> 
> ```
> balena run -it -e UDEV='on' --privileged balenalib/orange-pi-zero-alpine-node sh
> mount: mounting nodev on /sys/kernel/debug failed: No such file or directory
> ```
> 
> See https://jel.ly.fish/fc08efe4-02a4-4ae7-a8c1-42ea48f3c65f

When UDEV='on'.

**Comment by maggie0002** [comment]
@alexgg is this going to be an issue across all allwinner devices or just the 2.60 of Orange Pi Zero?

**Comment by maggie0002** [comment]
> @alexgg is this going to be an issue across all AllWinner devices or just the Orange Pi Zero? It appears to be an issue on the earlier version of Orange Pi Zero OS too (BalenaOS 2.53.9+rev1). Hoping it is something we can find a fix for as it prevents an important feature across the Orange Pi Zero OS family.

Appear to be mistaken, it is working on BalenaOS 2.53.9+rev1, but not 2.60.1+rev1. Not sure what happened during the last test.
