### ISSUE TITLE
Add support for Orange pi plus 2e

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-allwinner#16]
connects to https://github.com/resin-os/resin-os-device-support/issues/24

**Comment by spanceac** [comment]
The actual supported device is Orange Pi Plus2 which is a little different from Orange Pi Plus2e.

Probably the image works with Orange Pi Plus2e also but we need to test this assumption to be sure. We don't have a Orange Pi Plus2e board.

**Comment by thgreasi** [comment]
@spanceac according to [this forum post](https://forums.resin.io/t/orange-pi-plus-2e/3457) the Orange Pi Plus2 image works on Orange Pi Plus2e.
